# Generated by Django 3.1.7 on 2021-04-26 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, max_length=30)),
                ('descripcion', models.CharField(blank=True, default='', max_length=60)),
                ('forma_pago', models.CharField(max_length=15)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto_total', models.FloatField()),
                ('monto_facturacion', models.FloatField()),
                ('saldo_facturacion', models.FloatField()),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, max_length=30)),
                ('descripcion', models.CharField(blank=True, default='', max_length=60)),
                ('monto', models.FloatField()),
                ('nro_cuota', models.IntegerField()),
                ('fecha', models.DateField()),
                ('saldo', models.FloatField()),
                ('estado', models.CharField(choices=[('P', 'Pagado'), ('NP', 'No pagado')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('VIATICOS', 'Viáticos por viajes'), ('COMBUSTIBLE', 'Reposición de combustible'), ('LOGISTICA', 'Materiales para logística'), ('HONORARIOS', 'Honorarios profesionales'), ('ALQUILERES', 'Alquileres'), ('ARANCELES', 'Aranceles por plataformas'), ('OTROS', 'Otros')], default='OTROS', max_length=15)),
                ('detalle', models.CharField(blank=True, default='', max_length=75)),
                ('fecha', models.DateField()),
                ('gasto', models.FloatField(default=0)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.contrato')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.empleado')),
                ('registro', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.registrohora')),
            ],
        ),
    ]
