# Generated by Django 3.1.6 on 2021-06-01 23:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        ('proyectos', '0002_remove_entregable_responsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFacturacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=60)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto_facturar', models.FloatField()),
                ('estado', models.CharField(choices=[('FACTURADO', 'Facturado'), ('PENDIENTE FACTURACION', 'Pendiente de facturación'), ('PAGADO', 'Pagado')], default='PENDIENTE FACTURACION', max_length=25)),
                ('condicion_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.condicionpago')),
            ],
            options={
                'verbose_name': 'Plan de Facturacione',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, max_length=30)),
                ('descripcion', models.CharField(blank=True, default='', max_length=60)),
                ('monto', models.FloatField()),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('P', 'Pagado'), ('NP', 'No pagado')], max_length=10)),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('VIATICOS', 'Viáticos por viajes'), ('COMBUSTIBLE', 'Reposición de combustible'), ('LOGISTICA', 'Materiales para logística'), ('HONORARIOS', 'Honorarios profesionales'), ('ALQUILERES', 'Alquileres'), ('ARANCELES', 'Aranceles por plataformas'), ('OTROS', 'Otros')], default='OTROS', max_length=15)),
                ('detalle', models.CharField(blank=True, default='', max_length=75)),
                ('fecha', models.DateField(default=None, null=True)),
                ('gasto', models.FloatField(default=0)),
                ('contrato', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.contrato')),
                ('empleado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.empleado')),
                ('propuesta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gasto_propuesta', to='proyectos.propuesta')),
                ('registro', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.registrohora')),
            ],
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_factura', models.CharField(default='001-001-1234567', max_length=15)),
                ('nro_timbrado', models.IntegerField(default=123456789)),
                ('vigencia_desde', models.DateField(default=django.utils.timezone.now)),
                ('vigencia_hasta', models.DateField(default=django.utils.timezone.now)),
                ('nombre_cliente', models.CharField(max_length=100, null=True)),
                ('ruc', models.CharField(default='111111-1', max_length=15)),
                ('forma_pago', models.CharField(choices=[('CREDITO', 'Crédito'), ('CONTADO', 'Contado')], max_length=15)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField(default=django.utils.timezone.now)),
                ('monto_facturacion', models.FloatField(default=11111)),
                ('descripcion', models.CharField(blank=True, default='', max_length=60)),
                ('estado', models.CharField(choices=[('CREDITO', 'Crédito'), ('CONTADO', 'Contado')], default='PENDIENTE DE PAGO', max_length=20)),
                ('plan_facturacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.planfacturacion')),
            ],
        ),
    ]
