# Generated by Django 3.1.7 on 2021-05-20 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_propuesta_cliente'),
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFacturacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=60)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto_facturar', models.FloatField()),
                ('estado', models.CharField(choices=[('FACTURADO', 'Facturado'), ('PENDIENTE FACTURACION', 'Pendiente de facturación')], max_length=25)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.contrato')),
            ],
        ),
    ]
