# Generated by Django 3.1.7 on 2021-04-18 00:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20210418_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 4, 18, 0, 40, 13, 912055, tzinfo=utc)),
        ),
    ]
