# Generated by Django 3.1.7 on 2021-05-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_planfacturacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planfacturacion',
            options={'verbose_name': 'Plan de Facturacione'},
        ),
        migrations.AlterField(
            model_name='planfacturacion',
            name='estado',
            field=models.CharField(choices=[('FACTURADO', 'Facturado'), ('PENDIENTE FACTURACION', 'Pendiente de facturación')], default='PENDIENTE FACTURACION', max_length=25),
        ),
    ]
