# Generated by Django 3.1.7 on 2021-04-20 14:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_auto_20210419_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 4, 20, 14, 4, 17, 735289, tzinfo=utc)),
        ),
    ]
