# Generated by Django 3.1.7 on 2021-04-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_auto_20210420_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(),
        ),
    ]
