# Generated by Django 3.1.7 on 2021-04-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_auto_20210420_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('P', 'Pagado'), ('NP', 'No pagado')], max_length=10),
        ),
    ]
