# Generated by Django 3.1.7 on 2021-05-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta',
            name='fecha_aceptacion',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
