# Generated by Django 3.1.7 on 2021-05-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condicionpago',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='condicionpago',
            name='fecha_estimada',
        ),
        migrations.RemoveField(
            model_name='condicionpago',
            name='monto_pagar',
        ),
        migrations.RemoveField(
            model_name='condicionpago',
            name='porcentaje_pago',
        ),
        migrations.AddField(
            model_name='condicionpago',
            name='cantidad_pagos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='condicionpago',
            name='dias_vencimiento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='condicionpago',
            name='forma_pago',
            field=models.CharField(choices=[('CRE', 'Crédito'), ('CON', 'Contado')], default='CRE', max_length=3),
        ),
        migrations.AddField(
            model_name='condicionpago',
            name='monto_total',
            field=models.FloatField(default=0),
        ),
    ]
