# Generated by Django 3.1.7 on 2021-04-18 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        ('cuentas', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('horas_totales', models.IntegerField()),
                ('total', models.FloatField()),
                ('ganancia_esperada', models.FloatField()),
                ('aceptado', models.BooleanField(default=False, null=True)),
                ('fecha_aceptacion', models.DateField(default=None, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.area')),
                ('gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.empleado')),
            ],
        ),
    ]
