# Generated by Django 3.1.7 on 2021-04-18 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        ('proyectos', '0002_propuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropuestaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('horas_propuestas', models.IntegerField()),
                ('tarifa', models.FloatField()),
                ('total', models.FloatField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cargo')),
                ('propuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.propuesta')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.servicio')),
            ],
        ),
    ]
