# Generated by Django 3.1.7 on 2021-04-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_propuestadetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta',
            name='horas_totales',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
