# Generated by Django 3.1.7 on 2021-04-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_auto_20210418_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta',
            name='ganancia_esperada',
            field=models.FloatField(null=True),
        ),
    ]
