# Generated by Django 3.1.7 on 2021-04-19 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_auto_20210418_0229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propuestadetalle',
            old_name='horas_propuestas',
            new_name='horas_servicio',
        ),
    ]
