# Generated by Django 3.1.7 on 2021-04-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_auto_20210419_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='porcentaje_ganancia',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
    ]
