# Generated by Django 3.1.7 on 2021-04-20 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_propuesta_porcentaje_ganancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='propuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.propuesta'),
        ),
    ]
