from django.db import router
from django.urls import path
from apps.administracion.views import gastos, facturaciones, pagos


urlpatterns = [
	
    #gastos
    path(
        route='gastos/crear',
        view=gastos.crear_gasto,#CrearFactura.as_view(),
        name='gastos-crear'
    ),
    path(
        route='gastos/modificar/<str:pk>',
        view=gastos.actualizar_gasto,
        name='gastos-modificar'
    ),
    path(
        route='gastos/borrar/<str:pk>',
        view=gastos.borrar_gasto,
        name='gastos-borrar'
    ),
    path(
        route='gastos/listar',
        view=gastos.listar_gastos,
        name='gastos-listar'
    ),
    
    #facturaciones
    path(
        route='facturaciones/crear',
        view=facturaciones.crear_factura,#CrearFactura.as_view(),
        name='facturaciones-crear'
    ),
    path(
        route='facturaciones/modificar/<str:pk>',
        view=facturaciones.actualizar_factura,
        name='facturaciones-modificar'
    ),
    path(
        route='facturaciones/borrar/<str:pk>',
        view=facturaciones.borrar_factura,
        name='facturaciones-borrar'
    ),
    path(
        route='facturaciones/listar',
        view=facturaciones.listar_facturas,
        name='facturaciones-listar'
    ),
    path(
        route='facturaciones/contrato/<str:pk>/planes',
        view=facturaciones.listar_planes_facturacion,
        name='facturaciones-listar_planes'
    ),
    path(
        route='facturaciones/plan-facturacion/<str:pk>/emitir-factura',
        view=facturaciones.emitir_factura,
        name='facturaciones-emitir_factura'
    ),
    path(
        route='facturaciones/plan-facturacion/<str:pk>/factura',
        view=facturaciones.detalle_factura,
        name='facturaciones-detalle'
    ),
    path(
        route='facturaciones/pdf/<str:pk>',
        view=facturaciones.FacturaPdf.as_view(),
        name='factura'
    ),
    path(
        route='facturaciones/factura/<str:pk>/pagar',
        view=facturaciones.registrar_pago,
        name='facturaciones-registrar-pago'
    ),
    #Pagos
    path(
        route='pagos/crear',
        view=pagos.crear_pago,#CrearPago.as_view(),
        name='pagos-crear'
    ),
    path(
        route='pagos/modificar/<str:pk>',
        view=pagos.actualizar_pago,
        name='pagos-modificar'
    ),
    path(
        route='pagos/borrar/<str:pk>',
        view=pagos.borrar_pago,
        name='pagos-borrar'
    ),
    path(
        route='pagos/listar',
        view=pagos.listar_pagos,
        name='pagos-listar'
    ),
    path(
        route='pagos/detalle/<str:pk>',
        view=pagos.detalle_pago,
        name='pagos-detalle'
    ),
]