from django.urls import path
from apps.proyectos.views import clientes, contratos, equiposProyecto, registroHoras, propuestas


urlpatterns = [
	
    #Clientes
    path(
        route='clientes/crear',
        view=clientes.crear_cliente,#CrearCliente.as_view(),
        name='clientes-crear'
    ),
    path(
        route='clientes/modificar/<str:pk>',
        view=clientes.actualizar_cliente,
        name='clientes-modificar'
    ),
    path(
        route='clientes/borrar/<str:pk>',
        view=clientes.borrar_cliente,
        name='clientes-borrar'
    ),
    path(
        route='clientes/listar',
        view=clientes.listar_clientes,
        name='clientes-listar'
    ),

    #Contratos
    path(
        route='contratos/crear',
        view=contratos.crear_contrato,#CrearContrato.as_view(),
        name='contratos-crear'
    ),
    path(
        route='contratos/modificar/<str:pk>',
        view=contratos.actualizar_contrato,
        name='contratos-modificar'
    ),
    path(
        route='contratos/borrar/<str:pk>',
        view=contratos.borrar_contrato,
        name='contratos-borrar'
    ),
    path(
        route='contratos/listar',
        view=contratos.listar_contratos,
        name='contratos-listar'
    ),
    path(
        route='contratos/<str:pk>',
        view=contratos.detalle_contrato,
        name='contratos-detalle'
    ),
    #Equipos de Proyecto
    path(
        route='squads/crear',
        view=equiposProyecto.crear_equipo,#CrearEquipo.as_view(),
        name='squads-crear'
    ),
    path(
        route='squads/add/<str:pk>/',
        view=equiposProyecto.add_integrante,#AddMiembro.as_view(),
        name='squads-add'
    ),
    path(
        route='squads/modificar/<str:pk>',
        view=equiposProyecto.actualizar_equipo,
        name='squads-modificar'
    ),
    path(
        route='squads/borrar/<str:pk>',
        view=equiposProyecto.borrar_equipo,
        name='squads-borrar-equipo'
    ),
    path(
        route='squads/listar',
        view=equiposProyecto.listar_equipos,#ListaEquipos.as_view()
        name='squads-listar'
    ),
    path(
        route='squads/borrar-integrante/<str:pk>',
        view=equiposProyecto.borrar_integrante,
        name='squads-borrar-integrante'
    ),
    path(
        route='squads/<str:pk>/integrantes',
        view=equiposProyecto.listar_integrantes,
        name='squads-integrantes'
    ),
    #Registro de Horas
    path(
        route='registrohoras/crear',
        view=registroHoras.crear_registroHoras,
        name='registrohoras-crear'
    ),
    path(
        route='registrohoras/modificar/<str:pk>',
        view=registroHoras.actualizar_registroHora,
        name='registrohoras-modificar'
    ),
    path(
        route='registrohoras/borrar/<str:pk>',
        view=registroHoras.borrar_registroHora,
        name='registrohoras-borrar'
    ),
    path(
        route='registrohoras/listar',
        view=registroHoras.listar_registroHoras,
        name='registrohoras-listar'
    ),
    #Propuestas
    path(
        route='propuestas/crear',
        view=propuestas.crear_propuesta,
        name='propuestas-crear'
    ),
    path(
        route='propuestas/modificar/<str:pk>',
        view=propuestas.actualizar_propuesta,
        name='propuestas-modificar'
    ),
    path(
        route='propuestas/borrar/<str:pk>',
        view=propuestas.borrar_propuesta,
        name='propuestas-borrar'
    ),
    path(
        route='propuestas/listar/<str:estado>',
        view=propuestas.listar_propuestas,
        name='propuestas-listar'
    ),
    path(
        route='propuestas/<str:pk>',
        view=propuestas.detalle_propuesta,
        name='propuestas-detalle'
    ),
    path(
        route='propuestas/json/<str:pk>',
        view=propuestas.propuesta_json
    ),
    path(
        route='propuestas/<str:pk>/estado?<str:estado>',
        view=propuestas.estado_propuesta,
        name='propuestas-estado'
    ),
    path(
        route='propuestas/<str:pk>/asociar-cliente',
        view=propuestas.asociar_cliente_propuesta,
        name='propuestas-asociar-cliente'
    ),
    #Propuestas Detalle
    path(
        route='propuestas/<str:pk>/detalle/crear',
        view=propuestas.crear_propuestaDetalle,
        name='propuestasDetalle-crear'
    ),
    path(
        route='propuestas/detalle/modificar/<str:pk>',
        view=propuestas.actualizar_propuestaDetalle,
        name='propuestasDetalle-modificar'
    ),
    path(
        route='propuestas/detalle/borrar/<str:pk>',
        view=propuestas.borrar_propuestaDetalle,
        name='propuestasDetalle-borrar'
    ),
    path(
        route='propuestas/detalle/listar',
        view=propuestas.listar_propuestasDetalle,
        name='propuestasDetalle-listar'
    ),
    path(
        route='propuestas/<str:pk>/detalle/listar',
        view=propuestas.listar_detalle_propuesta,
        name='propuestasDetalle-detallePorPropuesta'
    ),
    #Entregable
    path(
        route='contratos/<str:pk>/entregables/crear',
        view=contratos.crear_entregable,
        name='entregables-crear'
    ),
    path(
        route='contratos/entregables/modificar/<str:pk>',
        view=contratos.actualizar_entregable,
        name='entregables-modificar'
    ),
    path(
        route='contratos/entregables/borrar/<str:pk>',
        view=contratos.borrar_entregable,
        name='entregables-borrar'
    ),
    path(
        route='contratos/entregables/listar/<str:pk>',
        view=contratos.listar_entregables,
        name='entregables-listar'
    ),
    path(
        route='contratos/entregables/<str:pk>',
        view=contratos.detalle_entregable,
        name='entregables-detalle'
    ),
    #Condiciones de Pago
    path(
        route='contratos/<str:pk>/condiciones-pago',
        view=contratos.crear_condicionPago,
        name='condicionPagos-crear'
    ),
    path(
        route='contratos/condiciones-pago/modificar/<str:pk>',
        view=contratos.actualizar_condicionPago,
        name='condicionPagos-modificar'
    ),
    path(
        route='contratos/condiciones-pago/borrar/<str:pk>',
        view=contratos.borrar_condicionPago,
        name='condicionPagos-borrar'
    ),
    path(
        route='contratos/<str:pk>/condiciones-pago/listar',
        view=contratos.listar_condicionPagos,
        name='condicionPagos-listar'
    ),
    path(
        route='contratos/condiciones-pago/<str:pk>',
        view=contratos.detalle_condicionPago,
        name='condicionPagos-detalle'
    ),
]